Fix release check
Make sure grep doesn't return a positive exit code on no match

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -44,14 +44,15 @@ jobs:
           OWNER: ${{ github.repository_owner }}
           REPO: ${{ github.event.repository.name }}
         run: |
-          curl -L \
-          -X GET \
+          curl -L -X GET \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer $GH_TOKEN" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           "https://api.github.com/repos/${{ env.OWNER }}/${{ env.REPO }}/releases/tags/${{ env.version_tag }}" \
           -o release.json
-          html_url=$(grep -Po -m 1 '(?:\G(?!^)",|"html_url":\s*)\s*"\K[^"]+' release.json)
+          # Don't return exit code 1 if no match found
+          # Credit https://stackoverflow.com/a/49627999/8120300
+          html_url=$({ grep -Po -m 1 '(?:\G(?!^)",|"html_url":\s*)\s*"\K[^"]+' release.json || test $? = 1; }| { grep -v grep || test $? = 1; })
           if [[ -z "$html_url" ]]; then
             echo "No release matching tag ${{ env.version_tag }} found" >> $GITHUB_STEP_SUMMARY
             echo "needs_release=true" >> $GITHUB_OUTPUT
@@ -69,8 +70,7 @@ jobs:
           REPO: ${{ github.event.repository.name }}
           BRANCH: main
         run: |
-          curl -L \
-          -X POST \
+          curl -L -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer $GH_TOKEN" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
@@ -92,8 +92,7 @@ jobs:
           OWNER: ${{ github.repository_owner }}
           REPO: ${{ github.event.repository.name }}
         run: |
-          curl -L \
-          -X POST \
+          curl -L -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer $GH_TOKEN" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
@@ -109,8 +108,7 @@ jobs:
           REPO: ${{ github.event.repository.name }}
         run: |
           sha256sum merged.hex > merged_sha256.sum
-          curl -L \
-          -X POST \
+          curl -L -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer $GH_TOKEN" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
@@ -125,8 +123,7 @@ jobs:
           OWNER: ${{ github.repository_owner }}
           REPO: ${{ github.event.repository.name }}
         run: |
-          curl -L \
-          -X POST \
+          curl -L -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer $GH_TOKEN" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
@@ -142,8 +139,7 @@ jobs:
           REPO: ${{ github.event.repository.name }}
         run: |
           sha256sum app_update.bin > app_update_sha256.sum
-          curl -L \
-          -X POST \
+          curl -L -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer $GH_TOKEN" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
