Update build and release workflows

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -21,31 +21,42 @@ jobs:
       - name: Git checkout
         uses: actions/checkout@v4
 
-      - name: Install curl
-        run: |
-          type -p curl >/dev/null || (sudo apt-get update && sudo apt-get install curl -y)
+      - name: Create build dir
+        run: mkdir -p build/zephyr/
 
-      - name: List caches present
+      # - name: Install curl
+      #   run: |
+      #     type -p curl >/dev/null || (sudo apt-get update && sudo apt-get install curl -y)
+
+      # - name: List caches present
+      #   env:
+      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #     OWNER: ${{ github.repository_owner }}
+      #     REPO: ${{ github.event.repository.name }}
+      #     BRANCH: main
+      #   run: |
+      #     curl -L \
+      #     -H "Accept: application/vnd.github+json" \
+      #     -H "Authorization: Bearer $GH_TOKEN" \
+      #     -H "X-GitHub-Api-Version: 2022-11-28" \
+      #     "https://api.github.com/repos/${OWNER}/${REPO}/actions/caches"
+
+      - name: Load build cache
+        uses: actions/cache/restore@v4
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           OWNER: ${{ github.repository_owner }}
           REPO: ${{ github.event.repository.name }}
           BRANCH: main
-        run: |
-          curl -L \
-          -H "Accept: application/vnd.github+json" \
-          -H "Authorization: Bearer $GH_TOKEN" \
-          -H "X-GitHub-Api-Version: 2022-11-28" \
-          "https://api.github.com/repos/${OWNER}/${REPO}/actions/caches"
-
-      - name: Load build cache
-        uses: actions/cache/restore@v4
         with:
           path: |
             build/zephyr/merged-${{ env.version_tag }}.hex.tar.xz
             build/zephyr/app_update-${{ env.version_tag }}.bin.tar.xz
           key: build-${{ env.version_tag }}
-          fail-on-cache-miss: true
+          restore-keys: |
+            build-${{ env.version_tag }}
+            build-
+          # fail-on-cache-miss: true
 
       - name: Upload merged.hex
         uses: Shopify/upload-to-release@v2.0.0
